### ISSUE TITLE
BMAB Upscale and With Model 노드 사용시 오류가 표시됩니다.

### ISSUE THREAD

**Issue by Neytiri7** [portu-sim/comfyui-bmab#2]
!!! Exception during processing!!! 'NoneType' object has no attribute 'pixels'
Traceback (most recent call last):
  File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\comfyui-bmab\bmab\nodes\upscaler.py", line 159, in upscale
    bind.pixels = utils.pil2tensor(bgimg.convert('RGB'))
    ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'pixels'

업스케일 하려고 하는 해상도를 직접 입력 또는 해상도 비율 계산 노드 사용시 오류가 표시됩니다.

**Comment by portu-sim** [comment]
수정되었습니다.

**Comment by Neytiri7** [comment]
!!! Exception during processing!!! 'NoneType' object has no attribute 'pixels'
Traceback (most recent call last):
  File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\comfyui-bmab\bmab\nodes\basic.py", line 140, in process
    bind.pixels = utils.pil2tensor(bgimg.convert('RGB'))
    ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'pixels'


베이직 노드를 사용하는데도 이렇게 표시됩니다.
